apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 669541320087.dkr.ecr.us-east-1.amazonaws.com/mydb:v1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345"
        ports:
        - containerPort: 8080
          protocol: TCP
